package trabalho.domainObjects;

import annotations.VisibleProperty;
import trabalho.propertiesUtils.PropertyKind;

public class Category extends DomainObject<Integer, Category> {

    private String _categoryName;
    private String _description;

    public Category(Integer id, String name, String description){
        super(id);
        this._categoryName = name;
        this._description = description;
        System.out.println("Category " + id + " loaded!");
    }

    public Category(String name, String description){
        super();
        this._categoryName = name;
        this._description = description;
    }
    
    @VisibleProperty(name="Id", kind=PropertyKind.Simple, isAutoGenerated=true, lookupClass=void.class)
    public int getCategoryId() { return getId(); }
    
    @VisibleProperty(name = "Category Name", kind = PropertyKind.Simple, isAutoGenerated=false, lookupClass=void.class)
    public String getCategoryName() { return _categoryName; }
    @VisibleProperty(name = "Category Name", kind = PropertyKind.Simple, isAutoGenerated=false, lookupClass=void.class)
    public void setCategoryName(String categoryName) { 
        markDirty();
        this._categoryName = categoryName;
    }

    @VisibleProperty(name = "Description", kind = PropertyKind.Simple, isAutoGenerated=false, lookupClass=void.class)
    public String getDescription() { return _description; }
    @VisibleProperty(name = "Description", kind = PropertyKind.Simple, isAutoGenerated=false, lookupClass=void.class)
    public void setDescription(String description) {
        markDirty();
        this._description = description;
    }

    @Override
    protected Category self() {
        return this;
    }

    @Override
    public String toString() {
        return "Category " + getId() + " - "
                + getCategoryName() + "\n\t"
                + getDescription();
    }
}
