package trabalho.domainObjects;

import java.util.Set;
import annotations.VisibleProperty;
import trabalho.domainObjects.primaryKeys.PkOrderDetails;
import trabalho.dataMappers.filters.FilterByProduct;
import trabalho.domainObjects.lazyLoaders.*;
import trabalho.propertiesUtils.PropertyKind;

public class Product extends DomainObject<Integer, Product>{

    private ILazySet<PkOrderDetails,OrderDetails> _orderDetails;
    private String _productName;
    private IValueHolder<Integer, Supplier> _supplier;
    private IValueHolder<Integer, Category> _category;
    private double _unitPrice;
    private int _unitsInStock;

    public Product() { super(); }

    public Product(Integer key, ILazySet<PkOrderDetails,OrderDetails> orderDetails,
            String productName, IValueHolder<Integer, Supplier> supplier,
            IValueHolder<Integer, Category> category, double unitPrice,
            int unitsInStock) {
        super(key);
        bindConstructorValues(productName, unitPrice, unitsInStock);
        _supplier = supplier;
        _category = category;
        _orderDetails = orderDetails;
        System.out.println("Product " + key + " loaded!");
    }

    public Product(String productName, Supplier supplier,
            Category category, double unitPrice,
            int unitsInStock) {
        super();
        bindConstructorValues(productName, unitPrice, unitsInStock);
        _orderDetails = new LazySet<PkOrderDetails, OrderDetails>();
        setSupplier(supplier);
        setCategory(category);
    }

    private void bindConstructorValues(String productName, double unitPrice,
            int unitsInStock) {
        _productName = productName;
        _unitPrice = unitPrice;
        _unitsInStock = unitsInStock;
    }

    @VisibleProperty(name="Product ID", kind = PropertyKind.Simple, isAutoGenerated=true)
    public Integer getProductId() { return getId(); }
    @Override
    public void setId(Integer id) {
        super.setId(id);
        _orderDetails = new LazySet<PkOrderDetails, OrderDetails>(
                new FilterByProduct(id),OrderDetails.class);
    }

    public Set<OrderDetails> getOrderDetails() { return _orderDetails.getImmutableSet(); }

    @VisibleProperty(name="Name", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getProductName() { return _productName; }

    @VisibleProperty(name="Name", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setProductName(String productName) {
        markDirty();
        this._productName = productName;
    }

    @VisibleProperty(name="Supplier", kind = PropertyKind.Complex, isAutoGenerated=false)
    public Supplier getSupplier() { return _supplier == null ? null : _supplier.get(); }
    @VisibleProperty(name="Supplier", kind = PropertyKind.Complex, isAutoGenerated=false)
    public void setSupplier(Supplier supplier) {
        markDirty();
        if (supplier != null && supplier.hasId()) {
            _supplier = new ValueHolder<Integer, Supplier>(supplier.getId(), supplier.mapper());
        } else {
            _supplier = new ValueHolder<Integer, Supplier>(supplier);
        }
    }

    @VisibleProperty(name="Category", kind = PropertyKind.Complex,isAutoGenerated=false)
    public Category getCategory() { return _category == null ? null : _category.get(); }
    @VisibleProperty(name="Category", kind = PropertyKind.Complex,isAutoGenerated=false)
    public void setCategory(Category category) {
        markDirty();
        if (category != null && category.hasId()) {
            _category = new ValueHolder<Integer, Category>(category.getId(),category.mapper());
        } else {
            _category = new ValueHolder<Integer, Category>(category);
        }
    }

    @VisibleProperty(name="Unit Price", kind = PropertyKind.Simple, isAutoGenerated=false)
    public Double getUnitPrice() { return _unitPrice; }
    @VisibleProperty(name="Unit Price", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setUnitPrice(double unitPrice) { 
        markDirty();
        this._unitPrice = unitPrice;
    }

    @VisibleProperty(name="Units In Stock", kind = PropertyKind.Simple, isAutoGenerated=false)
    public Integer getUnitsInStock() { return _unitsInStock; }
    @VisibleProperty(name="Units In Stock", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setUnitsInStock(int unitsInStock) { 
        markDirty();
        this._unitsInStock = unitsInStock;
    }

    @Override
    protected Product self() {
        return this;
    }
    
    @Override
    public String toString(){
        return "Product: " + getProductId() + " - " + getProductName() +
            " (Price: " + getUnitPrice() + " Stock: " + getUnitsInStock() + ")";
    }

}
