package trabalho.propertiesUtils;

import java.lang.reflect.Method;

public class PropertyInfo {

    private final Object _value;
    private final PropertyKind _kind;
    private final Method _hookMethod;
    private final Class<?> _lookupClass;
    private final boolean _autoGenerated;

    public PropertyInfo(Object value, PropertyKind kind, Class lookup, 
            boolean autoGenerated){
        this(null, value, kind, lookup, autoGenerated);
    }

    public PropertyInfo(Method method, PropertyKind kind, Class lookup,
            boolean autoGenerated){
        this(method, null, kind, lookup, autoGenerated);
    }

    private PropertyInfo(Method method, Object value, PropertyKind kind,
            Class lookup, boolean autoGenerated){
        _hookMethod = method;
        _value = value;
        _kind = kind;
        _lookupClass = lookup;
        _autoGenerated = autoGenerated;
    }

    public Object getValue() { return _value; }
    public PropertyKind getKind() { return _kind; }
    public Method getMethod() { return _hookMethod; }
    public Class getLookupClass() { return _lookupClass; }

    public boolean isAutoGenerated() { return _autoGenerated; }
}
