package trabalho.domainObjects;

import annotations.VisibleProperty;
import trabalho.propertiesUtils.PropertyKind;

public class Supplier extends DomainObject<Integer,Supplier>{

    private String _contactName;
    private String _companyName;
    private String _city;
    private String _country;
    private String _phone;

    public Supplier() { super(); }
    
    public Supplier(Integer id, String contact, String companyName,
            String city, String country, String phone){
        super(id);
        bindConstructorValues(companyName, contact, city, country, phone);
        System.out.println("Supplier " + id + " loaded!");
    }

    public Supplier(String contact, String companyName, String city,
            String country, String phone){
        super();
        bindConstructorValues(companyName, contact, city, country, phone);
    }

    private void bindConstructorValues(String companyName, String contact,
            String city, String country, String phone){
        _companyName = companyName;
        _contactName = contact;
        _city = city;
        _country = country;
        _phone = phone;
    }

    @VisibleProperty(name = "Company", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getCompanyName() { return _companyName; }
    @VisibleProperty(name = "Company", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setCompanyName(String companyName) {
        markDirty();
        this._companyName = companyName;
    }

    @VisibleProperty(name = "Contact Name", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getContactName() { return _contactName; }
    @VisibleProperty(name = "Contact Name", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setContactName(String contactName) {
        markDirty();
        this._contactName = contactName;
    }

    @VisibleProperty(name = "City", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getCity() { return _city; }
    @VisibleProperty(name = "City", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setCity(String city) { 
        markDirty();
        this._city = city;
    }

    @VisibleProperty(name = "Country", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getCountry() { return _country; }
    @VisibleProperty(name = "Country", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setCountry(String country) { 
        markDirty();
        this._country = country;
    }

    @VisibleProperty(name = "Phone", kind = PropertyKind.Simple, isAutoGenerated=false)
    public String getPhone() { return _phone; }
    @VisibleProperty(name = "Phone", kind = PropertyKind.Simple, isAutoGenerated=false)
    public void setPhone(String phone) { 
        markDirty();
        this._phone = phone;
    }

    @Override
    protected Supplier self() {
        return this;
    }

    @Override
    public String toString() {
        return "Supplier " + getId() + " - "
                + getCompanyName() + " - "
                + getPhone();
    }
}
