package trabalho.propertiesUtils;

import java.lang.reflect.Method;

public class PropertyInfo {

    private final Object _value;
    private final PropertyKind _kind;
    private final Method _hookMethod;
    private final Class<?> _lookupClass;
    private final boolean _autoGenerated;

    public PropertyInfo(Object value, PropertyKind kind, Class lookup, boolean autoGenerated){
        _value = value;
        _kind = kind;
        _hookMethod = null;
        _lookupClass = lookup;
        _autoGenerated = autoGenerated;
    }

    public PropertyInfo(Method method, PropertyKind kind, Class lookup, boolean autoGenerated){
        _value = null;
        _kind = kind;
        _hookMethod = method;
        _lookupClass = lookup;
        _autoGenerated = autoGenerated;
    }

    public Object getValue() { return _value; }

    public PropertyKind getKind() { return _kind; }

    public Method getMethod() { return _hookMethod; }

    public Class getLookupClass() { return _lookupClass; }

    public boolean isAutoGenerated() { return _autoGenerated; }
}
